#!/usr/bin/python3
from sys import argv
with open(argv[1]) as rs:
    for j in rs:
        num = int(j)
        for i in range(2,num):
            if num % i == 0:
                r = num // i
                print("{}={}*{}".format(num, i, r))
                break
